<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsHyperlocal
 * @author    CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */
?>
<div class="shiparea-table-wrapper">
    <?php
    echo $block->getButtonsHtml();
    echo $block->getGridHtml();
    ?>
</div>
<script>  require(
        [
            "jquery"
        ],
        function ($,
                  modal) {

            $('.cshyperlocal-shiparea-index').on("click", function (e) {
                if (!$(e.target).hasClass('shiparea-action')) {
                    $('.shiparea-action').removeClass('active');
                    $('.action-ul').removeClass('active');
                }
            });

            $('#cshyperlocalshiparea_table').on('click', '.shiparea-action', function () {
                if ($(this).parent().find('ul').hasClass('active')) {
                    $(this).parent().removeClass('active');
                    $(this).parent().find('ul').removeClass('active');
                } else {
                    $(this).parent().addClass('active');
                    $('.action-ul').removeClass('active');
                    $(this).parent().find('ul').addClass('active');
                }
            });


        });</script>
