<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_Affiliate
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license     http://cedcommerce.com/license-agreement.txt
 */

$referred_list = $this->getReferralList();
$earnedAmount=$block->pendingamount();
?>
<div class="referral-section-wrapper">
<div class="referral-pending">
	<div class="panel">
		<div class="panel-heading">
				<div class="info-heading"><center><?php echo __('Referrals Pending')?> <?php echo $block->pendingreferral() ?></center></div>
		</div>
	</div>
</div>


<div class="referral-acknowledged">
	<div class="panel">
		<div class="panel-heading">
				<div class="info-heading"><center><?php echo __('Referrals Acknowledged')?> <?php echo $block->registeredreferral() ?></center></div>
		</div>
	</div>
</div>

</div>
<?php echo $this->getChildHtml('user_sources') ?>
<?php
if(isset($referred_list) && $referred_list->count()>0){?>
	<div class="data-table-wrapper">
	<div class="block data-table-block-wrap">
	<div class="block-title">
	<strong>
		<?php echo __('Referred List')?>
	</strong>
	</div>
	<div class="block-content">
		<table class="data-table" id="my-orders-table">
			<thead>
				<tr>
					<th><?php echo __('Email Id');?></th>
					<th><?php echo __('Status');?></th>
					<th><?php echo __('Invited Date');?></th>
<!--					<th><?php echo __('Earned Amount'); ?></th>-->
				</tr>
			</thead>
			<tbody>
		<?php
		foreach($referred_list as $value){ ?>
				<tr>
						<td><?php echo $value["referred_email"] ?></td>
						<?php if($value["signup_status"]==0): ?>
							<td><?php echo __("Pending") ?></td>
						<?php else: ?>
							<td><?php echo __("Joined") ?></td>
						<?php endif ?>
						<td><?php echo $value["invite_date"] ?></td>
						<!--<td><?php echo $value["amount"] ?></td>-->
			   </tr>
		<?php }?>

			</tbody>
		</table>
		</div>
		</div>
	</div>

<?php if ($block->getPagerHtml()): ?>
<div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
<?php endif; ?>
<?php }else{?>
<h3><?php echo __('You had not referred any friends Via Email.')?></h3>
<?php }?>


<style>
table thead{
	background-color: #006BB4;
}
table tr th{
	font-weight: bold;
	color:white;
}
table tr td{
	width:12%;

}
</style>