<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_Affiliate
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license     http://cedcommerce.com/license-agreement.txt
 */
?>
<?php 
  $count = $block->getTotalSources();
  $fbcoll = $block->getCount('facebook');
  $googlecoll = $block->getCount('google');
  $twittercoll = $block->getCount('twitter');
  //$whatsappcoll = $block->getCount('whatsapp');
  $emailcoll = $block->getCount('email');
?>
<div class="aff-title">
      <h2><? echo __('Referral Reports') ?></h2>
</div>
<div class="referral-source-wrap">
	<div class="source-heading">
	  <h1><? echo __('Referral Sources') ?></h1>
	</div>
	<div class="social-referrel">
	  <ul>
	    <li class="google"><label><? echo __('Google : ') ?></label><span class="referral-counter"><?php  echo $googlecoll ?></span></li>
	    <li class="fb"><label><? echo __('Facebook : ') ?></label><span class="referral-counter"><?php  echo $fbcoll ?></span></li>
	    <li class="twitter"><label><? echo __('Twitter : ') ?></label><span class="referral-counter"><?php echo $twittercoll ?></span></li>
	    <li class="email"><label><? echo __('Emails : ') ?></label><span class="referral-counter"><?php  echo $emailcoll ?></span></li>
	  </ul>
	</div>
</div>