<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_DeliveryDate
 * @author     CedCommerce Core Team <connect@cedcommerce.com >
 * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */


?>

<?php
$csOrderHelper = $this->helper('Ced\CsOrder\Helper\Data');
$register = $this->registry;
$vorder = $register->registry('current_vorder');
?>
<?php /** @var $block \Magento\Sales\Block\Adminhtml\Order\View\Tab\Info */ ?>
<?php $_order = $block->getOrder() ?>


<section class="admin__page-section">
    <?php /*Vendor Delivery Date Method */ ?>
    <?php
    $vendorId = $this->session->getData('vendor_id');
    $orderId = $_order->getData('entity_id');
    $data = $this->itemCollectionFactory->create()
        ->addFieldToFilter('order_id', $orderId)->addFieldToFilter('vendor_id', $vendorId);
    $orderData = [];
    /*Dont display if data dosen't exist regarding vendor in order-item */
    if (!empty($data->getData())):

        foreach ($data->getData() as $key => $value) {
            if ($value['product_type'] == 'simple') {
                $orderData[$key]['name'] = $value['name'];
                $orderData[$key]['cs_deliverydate'] = isset($value['cs_deliverydate']) ? $value['cs_deliverydate'] : 'NA';
                $orderData[$key]['cs_deliverycomment'] = isset($value['cs_deliverycomment']) ? $value['cs_deliverycomment'] : 'NA';
                $orderData[$key]['cs_timestamp'] = isset($value['cs_timestamp']) ? $value['cs_timestamp'] : 'NA';
            }
        }
        ?>
        <div class="admin__page-section-item order-shipping-method" style="width:100%;">
            <div class="admin__page-section-item-title">
                <span class="title"><?php /* @escapeNotVerified */
                    echo __('Delivery Date Information') ?></span>
            </div>
            <table class="data-table admin__table-primary edit-order-table">
                <thead>
                <tr class="headings">
                    <th class="col-product">
                        <span><?= __("Product Name") ?></span>
                    </th>
                    <th class="col-status">
                    <span>
                        <?= __("DeliveryDate") ?>
                    </span>
                    </th>
                    <th class="col-price">
                        <span><?= __("Timestamp") ?></span>
                    </th>
                    <th class="col-price-original">
                        <span><?= __("Delivery Comment") ?></span>
                    </th>
                </tr>
                </thead>
                <tbody class="even">

                <?php foreach ($orderData as $key => $value) {

                    ?>
                    <tr>
                        <td class="col-product"><?php echo __($value['name']); ?></td>
                        <td class="col-product"><?php echo __($value['cs_deliverydate']); ?></td>
                        <td class="col-product"><?php echo __($value['cs_timestamp']); ?></td>
                        <td class="col-product"><?php echo __($value['cs_deliverycomment']); ?></td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
    <?php endif; ?>
</section>

