<?php $_source  = $block->getSource() ?>
<?php if ($_source): ?>
    <tr>
        <td class="label"><?php /* @escapeNotVerified */ echo $block->getShippingLabel() ?><div id="shipping_amount_adv"></div></td>
        <td>
            <input type="text"
                   name="creditmemo[shipping_amount]"
                   value="<?php /* @escapeNotVerified */ echo $block->getShippingAmount()?>"
                   class="input-text admin__control-text not-negative-amount"
                   id="shipping_amount" />
        </td>
    </tr>
    
    </tr>

<?php endif; ?>
