<?php 
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_Affiliate
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license     http://cedcommerce.com/license-agreement.txt
 */

$helper = $block->getHelper('Ced\Affiliate\Helper\Data');?>
<?php if($block->isProductPageEnable()):?>
<?php if($block->checkLoggedIn()):?>
<?php if($block->getAffiliateId()):?>
<div class="control">
	<?php if($helper->IsFbEnabled()):?>
            <a href="http://www.facebook.com/sharer.php?u=<?php echo urlencode($block->getCurrentUrl().'/?affiliate='.$block->getAffiliateId())?>" target="_blank">
        		<img src="<?php echo $block->getViewFileUrl('Ced_Affiliate/images/facebook.png');?>" alt="Facebook" height="30px" width="30px"/>
			</a>
            <?php endif;?>
            <?php if($helper->IsGoogleEnabled()):?>
            <a href="https://plus.google.com/share?url=<?php echo $block->getCurrentUrl().'/?affiliate='.$block->getAffiliateId()?>" target="_blank">
        		<img src="<?php echo $block->getViewFileUrl('Ced_Affiliate/images/google.png');?>" alt="Google" height="30px" width="30px"/>
			</a>
            <?php endif;?>
             <?php if($helper->IsTwitterEnabled()):?>
            <a href="https://twitter.com/share?url=<?php echo $block->getCurrentUrl().'/?affiliate='.$block->getAffiliateId() ?>&amp;text=Affiliate Banner Url;hashtags=Affiliate" target="_blank">
        		<img src="<?php echo $block->getViewFileUrl('Ced_Affiliate/images/twitter.png');?>" alt="Twitter" height="30px" width="30px"/>
			</a>
            <?php endif;?>

</div>
<?php endif;?>
<?php endif;?>
<?php endif;?>