<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_invoice = $block->getInvoice() ?>
<?php $_order   = $block->getOrder() ?>
<?php if ($_invoice && $_order): ?>
   <?php $flag =false;?>
<?php $arr =[];?>
<table>
<tr>
	<th><?php echo __('Seller');?></th>
	<th><?php echo __('GSTIN');?></th>
</tr>
<?php foreach ($_invoice->getAllItems() as $_item): ?>
            <?php if ($_item->getParentItem()) {
    continue;
}?>
<tr>
<?php $gstHelper = $this->helper('Ced\CsGst\Helper\Data');
$vendorId = $gstHelper->create('Ced\CsMarketplace\Model\Vproducts')->getVendorIdByProduct($_item->getProductId());

if($vendorId){
	
 	if(in_array($vendorId,$arr)){
 	
 	continue;
 	}
 	$arr[] = $vendorId;
	$Vendor =  $gstHelper->create('Ced\CsMarketplace\Model\Vendor')->load($vendorId);
?>
<td><?php echo $Vendor->getPublicName(); ?></td>
<td><?php echo $Vendor->getVendorGstin(); ?></td>
<?php	
	
}else{
	if(!$flag){
	$flag=true;
	?>
	<td><?php echo __('Admin'); ?></td>
	<td><?php echo $gstHelper->getGstinNo(); ?></td>

<?php }
}
?>
</tr>
<?php 
endforeach;
?>
</table>
    <table class="email-items">
        <thead>
            <tr>
                <th class="item-info">
                    <?= /* @escapeNotVerified */  __('Items'); ?>
                </th>
                <th class="item-igst">
                    <?= /* @escapeNotVerified */  __('IGST'); ?>
                </th>
                <th class="item-cgst">
                    <?= /* @escapeNotVerified */  __('CGST'); ?>
                </th>
                <th class="item-sgst">
                    <?= /* @escapeNotVerified */  __('SGST'); ?>
                </th>
                <th class="item-qty">
                    <?= /* @escapeNotVerified */  __('Qty'); ?>
                </th>
                <th class="item-subtotal">
                    <?= /* @escapeNotVerified */  __('Subtotal'); ?>
                </th>
                
                 
            </tr>
        </thead>
        <?php foreach ($_invoice->getAllItems() as $_item): ?>
            <?php
                if ($_item->getOrderItem()->getParentItem()) {
                    continue;
                }
            ?>
            <tbody>
                <?= $block->getItemHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
        <tfoot class="order-totals">
            <?= $block->getChildHtml('invoice_totals') ?>
        </tfoot>
    </table>
<?php endif; ?>
