<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_DeliveryDate
 * @author        CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license     https://cedcommerce.com/license-agreement.txt
 */

// @codingStandardsIgnoreFile
?>
<?php /** @var $block \Magento\Sales\Block\Order\Info */ ?>
<?php $_order = $block->getOrder() ?>
<?php /*Vendor Delivery Date Method */ ?>
<?php
$orderId = $_order->getData('entity_id');
$data = $this->itemCollectionFactory->create()
    ->addFieldToFilter('order_id', $orderId);
$orderData = [];
if (!empty($data->getData())):

    foreach ($data->getData() as $key => $value) {
        if ($value['product_type'] == 'simple' && isset($value['cs_deliverydate']) && $value['cs_deliverydate'] != '') {
            $orderData[$key]['name'] = $value['name'];
            $orderData[$key]['cs_deliverydate'] = $value['cs_deliverydate'];
            $orderData[$key]['cs_deliverycomment'] = $value['cs_deliverycomment'];
            $orderData[$key]['cs_timestamp'] = $value['cs_timestamp'];
        }
    }
    if(empty($orderData)){
        return '';
    }

    ?>
    <div class="admin__page-section-item order-shipping-method" style="width:100%;">
        <div class="block-title">
            <strong><?php /* @escapeNotVerified */
                echo __('Delivery Date Information') ?></strong>
        </div>
        <table class="data-table admin__table-primary edit-order-table">
            <thead>
            <tr class="headings">
                <th class="col-product">
                    <span><?= __("Product Name") ?></span>
                </th>
                <th class="col-status">
                    <span>
                        <?= __("DeliveryDate") ?>
                    </span>
                </th>
                <th class="col-price">
                    <span><?= __("Timestamp") ?></span>
                </th>
                <th class="col-price-original">
                    <span><?= __("Delivery Comment") ?></span>
                </th>
            </tr>
            </thead>
            <tbody class="even">

            <?php foreach ($orderData as $key => $value): ?>
                <tr>
                    <td class="col-product"><?php echo __($value['name']); ?></td>
                    <td class="col-product"><?php echo __($value['cs_deliverydate']); ?></td>
                    <td class="col-product"><?php echo __($value['cs_timestamp']); ?></td>
                    <td class="col-product"><?php echo __($value['cs_deliverycomment']); ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php endif; ?>
