<?php
$pointsData = $block->getPointsValue();
$subtotal = $this->subtotal();
?>
<div class="block">
	<div class="block-title">
		<div>
			<strong><?= /* @noEscape */ __('My Reward Points : ' . $subtotal); ?></strong>
		</div>
	</div>
	<div class="block-content">
		<div>
			<span><?= /* @noEscape */ __('One Point equals ' . $pointsData); ?></span>
		</div>
		<?php echo $block->getGridHtml(); ?>
	</div>
</div>