<?php $gridrecords = $block->getUsedPointCollection(); ?>
<div class="order-details-items ordered">
    <div class="order-title">
        <strong><?= $block->escapeHtml(__('Used')) ?></strong>
    </div>
    <?php if (count($gridrecords)>0) {?>
        <div class="table-wrapper order-items">
            <table class="data table table-order-items" id="used-point-table" ">
            <caption class="table-caption"><?php echo __('Used') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?php echo __('Points') ?></th>
                <th scope="col" class="col title"><?php echo __('Details') ?></th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach ($gridrecords as $gridrecord): ?>
                <tr>
                    <td data-th="<?= $block->escapeHtml(__('Points')) ?>" class="col id">
                        <?php echo $gridrecord->getPointUsed() ?>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Details')) ?>" class="col id">
                        <?php
                        if ($gridrecord->getOrderId()) {
                            echo "You used reward point for discount on Order ID: "; ?>
                            <a href="<?php echo $block->getViewOrderUrl($gridrecord->getOrderId())?>">
                                <?php echo $gridrecord->getOrderIncrementId() ?>
                            </a>
                            <?php
                        }
                        ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>

            </table>
        </div>
        <?php if ($block->getPagerHtml()): ?>
            <div class="order-products-toolbar toolbar bottom">
                <?php echo $block->getPagerHtml(); ?>
            </div>
        <?php endif ?>
    <?php } else {?>
        <div class="message info empty">
            <span><?php echo __('You have not used any reward point yet.'); ?></span>
        </div>
    <?php }?>
</div>


