<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsAdvTransaction
 * @author     CedCommerce Core Team <connect@cedcommerce.com >
 * @copyright   Copyright CEDCOMMERCE (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */
?>
<?php
$vid = $block->getVendorId();

$currencyCode = $this->storeManager->getStore(null)->getBaseCurrencyCode();
$values = $this->getDetails();

$val = $values['value'];

$keys = $this->getFees();
$vendorName = $this->getVendorName($vid);
?>
<div class="wrap_request">
    <div class="row">
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <?php echo('Transaction Details') ?>
                </div>
                <div class="panel-body">
                    <div class="panel-group" id="accordion">
                        <!-- Tab 1 Start -->
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a href="#collapseOne" data-parent="#accordion" data-toggle="collapse"
                                       aria-expanded="true" class="tab-item-link">
                                        <?php echo __('Order Information') ?>
                                    </a>
                                </h4>
                            </div>
                            <div class="panel-collapse collapse in" id="collapseOne" aria-expanded="true" style="">
                                <div class="panel-body">
                                    <div class="form-group">
                                        <div class="col-lg-6">


                                            <div class="form-group">
                                                <label><?php echo __('Vendor') ?> </label>
                                                <div class="shopurl_wrap">
                                                    <span class="shop_url"><?php //echo $shopurl?></span>
                                                    <span class="url_text">
                                                               <?php echo $vendorName; ?>
                                                            </span>
                                                </div>
                                                <div style="clear:both"></div>
                                            </div>

                                            <div class="form-group">
                                                <label><?php echo __('Order Id') ?> </label>
                                                <div class="shopurl_wrap">
                                                    <span class="shop_url"><?php //echo $shopurl?></span>
                                                    <span class="url_text">
                                                               <?php echo $val['order_id']; ?>
                                                            </span>
                                                </div>
                                                <div style="clear:both"></div>
                                            </div>

                                            <div class="form-group">
                                                <label><?php echo __('Payment Mode') ?> </label>
                                                <div class="shopurl_wrap">
                                                    <span class="shop_url"><?php //echo $shopurl?></span>
                                                    <span class="url_text">
                                                                <?php echo $val['pay_mode']; ?>
                                                            </span>
                                                </div>
                                                <div style="clear:both"></div>
                                            </div>

                                            <div class="form-group">
                                                <label><?php echo __('Grand Total') ?> </label>
                                                <div class="shopurl_wrap">
                                                    <span class="shop_url"><?php //echo $shopurl?></span>
                                                    <span class="url_text">
                                                                <?php echo $val['grand_total']; ?>
                                                            </span>
                                                </div>
                                                <div style="clear:both"></div>
                                            </div>
                                            <div class="form-group">
                                                <label><?php echo __('Shipping Fee of order') ?> </label>
                                                <div class="shopurl_wrap">
                                                    <span class="shop_url"><?php //echo $shopurl?></span>
                                                    <span class="url_text">
                                                                <?php echo $val['shipping_fee']; ?>
                                                            </span>
                                                </div>
                                                <div style="clear:both"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Tab 2 Start -->
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a href="#collapseTwo" data-parent="#accordion" data-toggle="collapse"
                                       aria-expanded="true" class="tab-item-link">
                                        <?php echo __('Fee Details') ?>
                                    </a>
                                </h4>
                            </div>
                            <div class="panel-collapse collapse in" id="collapseTwo" aria-expanded="true" style="">
                                <div class="panel-body">
                                    <div class="form-group">
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label><?php echo __('Commission Fee') ?> </label>
                                                <div class="shopurl_wrap">
                                                    <span class="shop_url"><?php //echo $shopurl?></span>
                                                    <span class="url_text">
                                                                <?php echo $val['commission_fee']; ?>
                                                            </span>
                                                </div>
                                                <div style="clear:both"></div>
                                            </div>
                                            <?php if (isset($val['ship_amount'])) {
                                                ?>
                                                <div class="form-group">
                                                    <label><?php echo __('Shipping Amount') ?> </label>
                                                    <div class="shopurl_wrap">
                                                        <span class="shop_url"><?php //echo $shopurl
                                                            ?></span>
                                                        <span class="url_text">
                                                                <?php echo $val['ship_amount']; ?>
                                                            </span>
                                                    </div>
                                                    <div style="clear:both"></div>
                                                </div>
                                                <?php
                                            }
                                            ?>
                                            <?php foreach ($keys as $k => $v) {
                                                ?>
                                                <div class="form-group">
                                                    <label><?php echo $v['field_label'] ?> </label>
                                                    <div class="shopurl_wrap">
                                                        <span class="shop_url"><?php //echo $shopurl
                                                            ?></span>
                                                        <span class="url_text">
                                                   	    <?php echo $val[$v['field_code']]; ?>
                                                   	  </span>
                                                    </div>
                                                    <div style="clear:both"></div>
                                                </div>
                                            <?php }
                                            ?>
                                            <div class="form-group">
                                                <label><?php echo __('Service Tax') ?> </label>
                                                <div class="shopurl_wrap">
                                                    <span class="shop_url"><?php //echo $shopurl?></span>
                                                    <span class="url_text">
                                                                <?php echo $val['service_tax']; ?>
                                                            </span>
                                                </div>
                                                <div style="clear:both"></div>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Tab 3 Start -->
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a href="#collapseThree" data-parent="#accordion" data-toggle="collapse"
                                       aria-expanded="true" class="tab-item-link">
                                        <?php echo __('Amount') ?>
                                    </a>
                                </h4>
                            </div>
                            <div class="panel-collapse collapse in" id="collapseThree" aria-expanded="true" style="">
                                <div class="panel-body">
                                    <div class="form-group">
                                        <div class="col-lg-6">
                                            <div class="form-group">
                                                <label><?php echo __('Total Amount') ?> </label>
                                                <div class="shopurl_wrap">
                                                    <span class="shop_url"><?php //echo $shopurl?></span>
                                                    <span class="url_text">
                                                                <?php echo $val['vendor_payment']; ?>
                                                            </span>
                                                </div>
                                                <div style="clear:both"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    .shopurl_wrap {
        float: right;
    }
</style>