<?php
/**
 * Webkul Software.
 *
 * @category   Webkul
 * @package    Webkul_Recurring
 * @author     Webkul Software Private Limited
 * @copyright  Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license    https://store.webkul.com/license.html
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php
$_product               = $block->getProduct();
$dataModel              = $block->getData("dataModel");
$recurringHelper        = $dataModel->getRecurringHelper();
$recurringData          = $recurringHelper->getRecurring($_product->getId());
$configData             = $recurringHelper->getConfigData();
$enabled                = $configData['enable'];
if ($enabled) {
    $enabled            = $recurringData['subscription'] ? $recurringData['subscription'] : $enabled;
    $enabled            = (!$_product->getData('subscription')) ? $_product->getData('subscription') : $enabled;
}
$allSubscriptionData    = $recurringHelper->getSubscriptionContent();
$buttonTitle            = __('Add to Cart');
$buttonTitleSubscribe   = __('Subscribe');
$dateRequired           = "<span class='wkrequired' >".__('Please select valid Date.')."</span>";
$isCustomerloggedIn     = $recurringHelper->getIsCustomerloggedIn();
if ($_product->isSaleable()): ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
            <div class="field qty">
                <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
                <div class="control">
                    <input type="number"
                        name="qty"
                        id="qty"
                        value="<?= /* @noEscape */ $block->getProductDefaultQty() * 1 ?>"
                        title="<?= $block->escapeHtml(__('Qty')) ?>"
                        class="input-text qty"
                        data-validate="<?= $block->escapeHtml(\Zend_Json::encode($block->getQuantityValidators())) ?>"
                        />
                </div>
            </div>
            <?php endif; ?>
            <div class="actions">
            
                <button type="submit"
                        title="<?= $block->escapeHtml($buttonTitle) ?>"
                        class="action primary tocart"
                        id="product-addtocart-button">
                    <span><?= $block->escapeHtml($buttonTitle) ?></span>
                </button>
            <?php
            if ($enabled) {
                if (count($allSubscriptionData)) {
                    if ($isCustomerloggedIn) {
                        ?>
                    <button type="button"
                            title="<?= $block->escapeHtml($buttonTitleSubscribe) ?>"
                            class="action primary subscribetocart"
                            id="product-subscribe-button">
                        <span><?= $block->escapeHtml($buttonTitleSubscribe) ?></span>
                    </button>
                        <?php
                    } else {
                          $buttonTitleLogin   = __('Login To Subscribe');
                          $url = $block->getUrl("recurring/customer/redirect");
                          $url .= "?url=".$block->getRequest()->getUriString();
                        ?>
                        <button data-url="<?= /* @noEscape */ $url ?>" type="button"
                                title="<?= $block->escapeHtml($buttonTitleSubscribe) ?>"
                                class="action primary login-to-subscribe subscribetocart"
                                id="login-to-subscribe">
                            <span><?= $block->escapeHtml($buttonTitleLogin) ?></span>
                        </button>
                        <?php
                    }
                }
            }
            ?>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
    <?php endif; ?>
    <?php
    if ($block->isRedirectToCartEnabled()): ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
    <?php else: ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
    <?php endif; ?>
<script>
    window.subscription = <?= /* @noEscape */ \Zend_Json::encode($allSubscriptionData); ?>;
    window.requiredTitle = <?= /* @noEscape */ \Zend_Json::encode($dateRequired); ?>;
</script>

<div id="subscription-component" data-bind="scope:'subscription-content'" class="field">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "#subscription-component": {
            "Magento_Ui/js/core/app":  <?= /* @noEscape */ $block->getJsLayout();?>
        }
    }
    </script>
</div>

