<?php 

//$format = Mage::app()->getLocale()->getDateStrFormat(Mage_Core_Model_Locale::FORMAT_TYPE_SHORT);
$post = $this->getRequest()->getPost();
?>
<div class="content-header">
    <table cellspacing="0" width='100%'>
        <tr>
               <td class="form-buttons" style='float:right'><?php echo $this->getButtonsHtml() ?></td>
        </tr>
    </table>
</div>


<div>
    <?php echo $this->getGridHtml() ?>
</div>


<script type="text/javascript">
    function filter()
    {
        var action = '<?php echo $this->getFilterActionUrl(); ?>';
        var from = document.getElementById('from').value;
        var to = document.getElementById('to').value;
        window.location.href = action+'from/'+from+'/to/'+to;
    }
    function exportCsv(){
        var action = '<?php echo $this->getExportCsvAction(); ?>';
        var from = '<?= $block->getRequest()->getParam("from")?>';
        var to = '<?= $block->getRequest()->getParam("to")?>';
        window.location.href = action+'from/'+from+'/to/'+to;
    }
</script>

<script>
     require([
         "jquery",
         "mage/calendar"
    ], function($){
        $("#to").calendar({
             buttonText:"<?php echo __('Select Date') ?>",
             dateFormat: 'yy-mm-dd',
        });
      });
    require([
             "jquery",
             "mage/calendar"
        ], function($){
            $("#from").calendar({
                 buttonText:"<?php echo __('Select Date') ?>",
                 dateFormat: 'yy-mm-dd',
            });
          });
</script>
<style>
    .form-list{
        width: 100%;
    }
    .text-box {
        width: 220px;
        height:37px;
    }
    #vendor-name{
    	height:37px;
    }
    .select{
        width: 220px;
        height:37px;   
    }
    .label{
    	color: black;
    }
</style>