<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_Affiliate
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license     http://cedcommerce.com/license-agreement.txt
 */

// @codingStandardsIgnoreFile

?>
<div class="affiliate-login-container login-container affiliate-forgot-password">
    <div class="block block-forgot-password block-customer-login">
        <div class="block-title">
            <strong><?php echo("Forgot Password") ?></strong>
        </div>
        <div class="block-content">
            <form class="form password forget"
                  action="<?php /* @escapeNotVerified */ echo $block->getUrl('*/*/forgotpasswordpost') ?>"
                  method="post"
                  id="form-validate"
                  data-mage-init='{"validation":{}}'>
                <fieldset class="fieldset" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
                    <div class="field note"><?php /* @escapeNotVerified */ echo __('Please enter your email address below to receive a password reset link.'); ?></div>
                    <div class="field email required">
                       <!--  <label for="email_address" class="label"><span><?php /* @escapeNotVerified */ //echo __('Email') ?></span></label> -->
                        <div class="control">
                            <input type="email" placeholder="Email" name="email" alt="email" id="email_address" class="input-text" value="<?php echo $block->escapeHtml($block->getEmailValue()) ?>" data-validate="{required:true, 'validate-email':true}">
                        </div>
                    </div>
                    <?php echo $block->getChildHtml('form_additional_info'); ?>
                </fieldset>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit" class="action submit primary"><span><?php /* @escapeNotVerified */ echo __('Reset My Password') ?></span></button>
                    </div>
                    <div class="secondary">
                        <a class="action back" href="<?php /* @escapeNotVerified */ echo $block->getLoginUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Go back') ?></span></a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
