<?php
/**
 * Webkul Software.
 *
 * @category   Webkul
 * @package    Webkul_Recurring
 * @author     Webkul Software Private Limited
 * @copyright  Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license    https://store.webkul.com/license.html
 */
?>
<script>
  require([
       'Magento_Customer/js/customer-data'
   ], function (customerData) {
       var sections = ['cart'];
       customerData.invalidate(sections);
       customerData.reload(sections, true);
   });
</script>