<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsPromotions
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */

?>
<form id="edit_form" action="<?php echo $this->getSaveUrl() ?>" method="post" novalidate="novalidate">
  <div class="entry-edit cart-rule-view" id="cart_rule_view">
  	<?php echo $this->getChildhtml("promo_quote_edit_tabs");  ?>
  </div>
</form>
<script>
require([
    'jquery',
    'Magento_Ui/js/modal/confirm',
    'mage/backend/form',
    'mage/backend/validation',
], function($, confirm){

    window.setLocation = function (url) {
            window.location.href = url;
        };
     window.deleteConfirm = function (message, url) {
            confirm({
                content: message,
                actions: {
                    confirm: function () {
                        setLocation(url);
                    }
                }
            });

            return false;
        };

    window.confirmSetLocation = window.deleteConfirm;

    
    $('#edit_form').form()
        .validation({
            validationUrl: '',
            highlight: function(element) {
                var detailsElement = $(element).closest('details');
                if (detailsElement.length && detailsElement.is('.details')) {
                    var summaryElement = detailsElement.find('summary');
                    if (summaryElement.length && summaryElement.attr('aria-expanded') === "false") {
                        summaryElement.trigger('click');
                    }
                }
                $(element).trigger('highlight.validate');
            }
        });

});



</script>
<style>
.fieldset > .field:not(.choice) > .label {
    width: 20% !important;
}
.legend {
    border-bottom: 1px solid #cac3b4;
    box-sizing: border-box;
    float: left;
    margin: 0 0 18px;
    padding: 0;
    position: static;
    width: 100%;
}
.abs-margin-for-forms-desktop, .fieldset .legend, .column:not(.sidebar-main) form .actions-toolbar, .column:not(.sidebar-additional) form .actions-toolbar, .login-container .fieldset::after {
    margin-left: 0% !important;
}
.legend span {
    color: #303030;
    display: inline-block;
    font-size: 1.7rem;
    font-weight: 600;
    padding: 7px 0 10px;
}
.tree-store-scope .admin__field[class*="field-w"], .tree-store-scope .admin__field[class*="field-sg"] {
    margin: 0px !important;
}

.admin__field:not(.admin__field-option) > .admin__field-label::before {
    margin-left: 0 !important;
}

.tree-store-scope .field-s_1 .control {
    margin: 0;
    width: 60%;
    float: left;
}

.tree-store-scope .field-s_1 .label {
    margin-left: 0;
    padding-right: 30px;
    padding-top: 0;
    width: 20%;
    float: left;
}
.label{
    color: black !important;
}
</style>

