<?php 
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_Affiliate
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license     http://cedcommerce.com/license-agreement.txt
 */
if($block->getBanner()):?>
	<?php if($block->getBanner()->getBannerType()=='image'):?>
	 <div class="image_box">
			 <img src="<?php echo $block->getImageSrc().$block->getBanner()->getBannerData()?>" width="50%" height="50%">
     </div>
     <?php else:?>
     <div class="video_box">
      <iframe width="420" height="315" src="<?php echo $block->getImageSrc().$block->getBanner()->getBannerData()?>">
		</iframe> 
			
     </div>
     <?php endif;?>
<?php endif;?>
<style>
.image_box > img {
    float: left;
    margin-right:10px;
}
</style>
<script>
require([
         'jquery',
         'mage/mage'
     ], function($){

       $("#banner_image").removeClass('required-entry');

     });
</script>
