<?php

/**
 * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the End User License Agreement (EULA)
  * that is bundled with this package in the file LICENSE.txt.
  * It is also available through the world-wide-web at this URL:
  * http://cedcommerce.com/license-agreement.txt
  *
  * @category    Ced
  * @package     Ced_CsStorePickup
  * @author   	 CedCommerce Core Team <connect@cedcommerce.com >
  * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license      http://cedcommerce.com/license-agreement.txt
  */
?>
<?php /** @var $block \Magento\Shipping\Block\Adminhtml\View */ ?>
<?php $order = $block->getOrder()?>
<?php $vorder = $block->getvOrder();?>
<?php $storepickuphelper = $this->helper('Ced\StorePickup\Helper\Data');?>
<?php $vstorepickuphelper = $this->helper('Ced\CsStorePickup\Helper\Data');?>

<?php /* Shipping Method */ ?>
<div class="admin__page-section-item order-shipping-method">
	<div class="admin__page-section-item-title">
		<span class="title"><?php /* @escapeNotVerified */ echo __('Shipping &amp; Handling Information') ?></span>
	</div>
	<div class="admin__page-section-item-content">
        <?php  if ($order->getTracksCollection()->count()) : ?>
            <p>
			<a href="#" id="linkId"
				onclick="popWin('<?php /* @escapeNotVerified */ echo $this->helper('Magento\Shipping\Helper\Data')->getTrackingPopupUrlBySalesModel($order) ?>','trackorder','width=800,height=600,resizable=yes,scrollbars=yes')"
				title="<?php /* @escapeNotVerified */ echo __('Track Order') ?>"><?php /* @escapeNotVerified */ echo __('Track Order') ?></a>
		</p>
        <?php endif; ?>
        <?php if ($vstorepickuphelper->getCurrentVendorOrder()->getCarrier()=='storepickupshipping'):?>

        <?php $storepickupdata = $vstorepickuphelper->getStorePickupData($order)?>
        <?php if ($storepickupdata && is_array($storepickupdata) && count($storepickupdata) > 2):?>
        <?php $store_data = $storepickuphelper->getPickupStore($storepickupdata);?>
        <p>
			<span><b><?= __('Store Name'); ?></b></span> <span><?= $store_data->getStoreName(); ?></span>
		</p>
		<p>
			<span><b><?= __('Store Address'); ?></b></span> <span><?= $store_data->getStoreAddress(); ?></span>
		</p>
		<p>
			<span><b><?= __('Store City'); ?></b></span> <span><?= $store_data->getStoreCity(); ?></span>
		</p>
		<p>
			<span><b><?= __('Store Country'); ?></b></span> <span><?= $storepickuphelper->getCountryName($store_data->getStoreCountry()); ?></span>
		</p>
		<p>
			<span><b><?= __('Store Zip Code'); ?></b></span> <span><?= $store_data->getStoreZcode(); ?></span>
		</p>
		<p>
			<span><b><?= __('Store Contact Number'); ?></b></span> <span><?= $store_data->getStorePhone(); ?></span>
		</p>

		<br>
		<p>
			<span><b><?= __('Store Pickup Date'); ?></b></span> <span><?= $storepickupdata['pickup_date']; ?></span>
		</p>

        <?php endif;?>
        <?php endif;?>

        <?php if ($vorder->getShippingDescription()): ?>
            <strong><?= $vorder->getShippingDescription() ?></strong>

            <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingPriceIncludingTax()): ?>
                <?php $_excl = $block->displayShippingPriceInclTax($vorder); ?>
            <?php else: ?>
                <?php $_excl = $block->displayPriceAttribute('shipping_amount', false, ' '); ?>
            <?php endif; ?>
            <?php $_incl = $block->displayShippingPriceInclTax($vorder); ?>

            <?php /* @escapeNotVerified */ echo $_excl; ?>
            <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingBothPrices() && $_incl != $_excl): ?>
                (<?php /* @escapeNotVerified */ echo __('Incl. Tax'); ?> <?php /* @escapeNotVerified */ echo $_incl; ?>)
            <?php endif; ?>
        <?php else: ?>
            <?php /* @escapeNotVerified */ echo __('No shipping information available'); ?>
        <?php endif; ?>

    </div>
</div>
