<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_DeliveryDate
 * @author 		CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license     http://cedcommerce.com/license-agreement.txt
 */

// @codingStandardsIgnoreFile

?>
<?php  $_order = $block->getShipment()->getOrder() ?>
<?php echo $block->getChildHtml('order_info') ?>
<section class="admin__page-section order-shipment-billing-shipping">
    <div class="admin__page-section-title">
        <span class="title"><?php echo __('Payment &amp; Shipping Method') ?></span>
    </div>
    <div class="admin__page-section-content">

        <?php /* Billing Address */ ?>
        <div class="admin__page-section-item order-payment-method">
            <div class="admin__page-section-item-title">
                <span class="title"><?php echo __('Payment Information') ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <div><?php echo $block->getChildHtml('order_payment') ?></div>
                <div class="order-payment-currency"><?php echo __('The order was placed using %1.', $_order->getOrderCurrencyCode()) ?></div>
            </div>

            <?php
            if ($this->helper('Ced\DeliveryDate\Helper\ConfigData')->ddShowOn('shipment')):
                ?>
            <div class="admin__page-section-item-title"></div>

            <div class="admin__page-section-item-title">
                <span class="title"><?php echo __('Delivery Date Information') ?></span>
            </div>
                <div class="admin__page-section-item-content">
                    <?php
                    $deliveryComment = $_order->getData('cedDeliveryComment');
                    $deliveryTimestamp = $_order->getData('cedTimestamp');
                    if ($_order->getData('cedDeliveryDate') != '0000-00-00 00:00:00'){
                        $deliveryDate = $block->formatDate(
                            $_order->getData('cedDeliveryDate'),
                            \IntlDateFormatter::MEDIUM,
                            true
                        );
                    }
                    ?>
                    <div class="admin__page-section-item-content">

                        <?php if(isset($deliveryDate)):?>
                            <p>
                                <strong><?php echo(__('Delivery Date : ')); ?></strong>
                                <span><?php echo(__($deliveryDate)); ?></span>
                            </p>
                        <?php endif; ?>
                        <?php if(isset($deliveryTimestamp)):?>
                            <p>
                                <strong><?php echo(__('Delivery Timestamp : ')); ?></strong>
                                <span><?php echo(__($deliveryTimestamp)); ?></span>
                            </p>
                        <?php endif; ?>
                        <?php if(isset($deliveryComment) && $deliveryComment != ''):?>
                            <p>
                                <strong><?php echo(__('Delivery Comment : ')); ?></strong>
                                <span><?php echo(__($deliveryComment)); ?></span>
                            </p>
                        <?php endif; ?>
                    </div>

                </div>
            <?php endif; ?>
        </div>

        <?php /* Shipping Address */ ?>
        <div class="admin__page-section-item order-shipping-address">
            <div class="admin__page-section-item-title">
                <span class="title"><?php echo __('Shipping and Tracking Information') ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <div class="shipping-description-wrapper">
                    <?php if ($block->getShipment()->getTracksCollection()->count()): ?>
                        <p>
                            <a href="#" id="linkId" onclick="popWin('<?php echo $this->helper('Magento\Shipping\Helper\Data')->getTrackingPopupUrlBySalesModel($block->getShipment()) ?>','trackshipment','width=800,height=600,resizable=yes,scrollbars=yes')" title="<?php echo __('Track this shipment') ?>"><?php echo __('Track this shipment') ?></a>
                        </p>
                    <?php endif; ?>
                    <div class="shipping-description-title">
                        <?php echo $block->escapeHtml($_order->getShippingDescription()) ?>
                    </div>

                    <?php echo __('Total Shipping Charges'); ?>:

                    <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingPriceIncludingTax()): ?>
                        <?php $_excl = $block->displayShippingPriceInclTax($_order); ?>
                    <?php else: ?>
                        <?php $_excl = $block->displayPriceAttribute('shipping_amount', false, ' '); ?>
                    <?php endif; ?>
                    <?php $_incl = $block->displayShippingPriceInclTax($_order); ?>

                    <?php echo $_excl; ?>
                    <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingBothPrices() && $_incl != $_excl): ?>
                        (<?php echo __('Incl. Tax'); ?> <?php echo $_incl; ?>)
                    <?php endif; ?>
                </div>
                <?php if ($block->canCreateShippingLabel()): ?>
                    <p>
                        <?php echo $block->getCreateLabelButton()?>
                        <?php if ($block->getShipment()->getShippingLabel()): ?>
                            <?php echo $block->getPrintLabelButton() ?>
                        <?php endif ?>
                        <?php if ($block->getShipment()->getPackages()): ?>
                            <?php echo $block->getShowPackagesButton() ?>
                        <?php endif ?>
                    </p>
                <?php endif ?>
                <?php echo $block->getChildHtml('shipment_tracking') ?>

                <?php echo $block->getChildHtml('shipment_packaging') ?>
                <script>
                    require([
                        'prototype'
                    ], function () {

                        setTimeout(function () {
                            packaging.setConfirmPackagingCallback(function () {
                                packaging.sendCreateLabelRequest();
                            });
                            packaging.setLabelCreatedCallback(function (response) {
                                setLocation("<?php echo $block->getUrl(
                                    'adminhtml/order_shipment/view',
                                    ['shipment_id' => $block->getShipment()->getId()]
                                ); ?>");
                            });
                        }, 500);

                    });
                </script>
            </div>
        </div>
    </div>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php echo __('Items Shipped') ?></span>
    </div>
    <?php echo $block->getChildHtml('shipment_items') ?>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php echo __('Order Total') ?></span>
    </div>
    <div class="admin__page-section-content">
        <?php echo $block->getChildHtml('shipment_packed') ?>

        <div class="admin__page-section-item order-comments-history">
            <div class="admin__page-section-item-title">
                <span class="title"><?php echo __('Shipment History') ?></span>
            </div>
            <div class="admin__page-section-item-content"><?php echo $block->getChildHtml('order_comments') ?></div>
        </div>
    </div>
</section>
