<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_DeliveryDate
 * @author 		CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license     http://cedcommerce.com/license-agreement.txt
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Shipping\Block\Adminhtml\View */ ?>
<?php $order = $block->getOrder() ?>
<?php if ($order->getIsVirtual()) : return '';endif; ?>

<?php /* Shipping Method */ ?>
<div class="admin__page-section-item order-shipping-method">
    <div class="admin__page-section-item-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Shipping &amp; Handling Information') ?></span>
    </div>
    <div class="admin__page-section-item-content">
        <?php  if ($order->getTracksCollection()->count()) : ?>
            <p><a href="#" id="linkId" onclick="popWin('<?php /* @escapeNotVerified */ echo $this->helper('Magento\Shipping\Helper\Data')->getTrackingPopupUrlBySalesModel($order) ?>','trackorder','width=800,height=600,resizable=yes,scrollbars=yes')" title="<?php /* @escapeNotVerified */ echo __('Track Order') ?>"><?php /* @escapeNotVerified */ echo __('Track Order') ?></a></p>
        <?php endif; ?>
        <?php if ($order->getShippingDescription()): ?>
            <strong><?php echo $block->escapeHtml($order->getShippingDescription()) ?></strong>

            <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingPriceIncludingTax()): ?>
                <?php $_excl = $block->displayShippingPriceInclTax($order); ?>
            <?php else: ?>
                <?php $_excl = $block->displayPriceAttribute('shipping_amount', false, ' '); ?>
            <?php endif; ?>
            <?php $_incl = $block->displayShippingPriceInclTax($order); ?>

            <?php /* @escapeNotVerified */ echo $_excl; ?>
            <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingBothPrices() && $_incl != $_excl): ?>
                (<?php /* @escapeNotVerified */ echo __('Incl. Tax'); ?> <?php /* @escapeNotVerified */ echo $_incl; ?>)
            <?php endif; ?>
        <?php else: ?>
            <?php /* @escapeNotVerified */ echo __('No shipping information available'); ?>
        <?php endif; ?>
    </div>
</div>

<?php /* Delivery Date Method */
    if ($this->helper('Ced\DeliveryDate\Helper\ConfigData')->ddShowOn('order')):
        ?>
    <div class="admin__page-section-item order-shipping-method">
    <!--    <hr>-->
            <div class="admin__page-section-item-title">
    <!--            <strong class="title">--><?php ///* @escapeNotVerified */ echo __('Delivery Date Information') ?><!--</strong>-->
            </div>
        <?php
        $deliveryComment = $order->getData('cedDeliveryComment');
        $deliveryTimestamp = $order->getData('cedTimestamp');
        if ($order->getData('cedDeliveryDate') != '0000-00-00 00:00:00'){
            $deliveryDate = $block->formatDate(
                $order->getData('cedDeliveryDate'),
                \IntlDateFormatter::MEDIUM,
                true
            );
        }
        ?>
        <div class=" ">

            <?php if(isset($deliveryDate) ):?>
                <p>
                    <strong><?php echo(__('Delivery Date : ')); ?></strong>
                    <span><?php echo(__($deliveryDate)); ?></span>
                </p>
            <?php endif; ?>
            <?php if(isset($deliveryTimestamp)):?>
                <p>
                    <strong><?php echo(__('Delivery Timestamp : ')); ?></strong>
                    <span><?php echo(__($deliveryTimestamp)); ?></span>
                </p>
            <?php endif; ?>
            <?php if(isset($deliveryComment)  && $deliveryComment != ''):?>
                <p>
                    <strong><?php echo(__('Delivery Comment : ')); ?></strong>
                    <span><?php echo(__($deliveryComment)); ?></span>
                </p>
            <?php endif; ?>
        </div>
    </div>

    <?php endif; ?>
