<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_Affiliate
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license     http://cedcommerce.com/license-agreement.txt
 */

$coupons = $this->getCollection();

if(isset($coupons) && $coupons->count()>0){?>
<div style="overflow-x:auto; margin-top:20px">
		<table class="data-table" id="my-orders-table">
			<thead>
				<tr>
					<th><?php echo __('S.no');?></th>
					<th><?php echo __('Coupon Code');?></th>
					<th><?php echo __('Amount');?></th>
					<th><?php echo __('Created At');?></th>
					<th><?php echo __('Valid Till');?></th>
					<th><?php echo __('Status');?></th>
					<th><?php echo __('Purchase Required');?></th>
				</tr>
			</thead>
			<tbody>
		<?php $i=1; ?>
		<?php foreach($coupons as $value): ?>
		    <?php $coupon_used = $block->getDiscountCouponStatus($value["coupon_code"]);
		        if($coupon_used == 0){
		            $status = 'Unused';
		        }else{
		            $status = 'Used';
		        }
		    ?>
				<tr>
						<td><?php echo  $i; $i++ ?></td>
						<td><?php echo $value["coupon_code"] ?></td>
						<td><?php echo $block->getFormattedPrice($value["amount"]) ?></td>
						<td><?php echo $value["created_at"] ?></td>
						<td><?php echo $value["expiration_date"] ?></td>
						<td><?php echo $status ?></td>
						<td><?php echo $value["cart_amount"] ?></td>
			   </tr>
		<?php endforeach; ?>
			</tbody>
		</table>
</div>
<?php if ($block->getPagerHtml()): ?>
<div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
<?php endif; ?>
<?php }else{?>
<h3>You don't have any discount coupons.</h3>
<?php }?>


<style>
table thead{
	background-color: #006BB4;
}
table tr th{
	font-weight: bold;
	color:white;
}
table tr td{
	width:12%;

}
</style>