<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Recurring
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
 <input class="admin__control-text" data-mage-init='{
        "Webkul_Recurring/js/plan-element":{}
    }' id="planid" type="hidden"  name="product[plans]" data-form-part="product_form"/>
