<?php 
$id_layout = (int) $this->getRequest()->getParam("layout_id"); 
$layout_name = $this->getLayoutNameById($id_layout);
?>

<form action="" method="post" enctype="multipart/form-data" id="form_new_layout">
    <input type="hidden" id="form_key" name="form_key" value="<?php echo $this->getFormKey(); ?>" />
    <input type="hidden" id="layout_id" name="layout_id" value="<?php echo $id_layout; ?>" />
    <input type="hidden" id="store_id" name="store_id" value="<?php echo $this->getStoreId(); ?>" />
    <fieldset class="admin__fieldset"> 
       <div class="admin__field">
            <label class="admin__field-label" for="title">
                <span>
                    <span class="vss_required">*</span> <?php echo __("Layout Name"); ?>
                </span>
            </label>
            <div class="admin__field-control">
                <div class="admin__control">
                    <input type="text" class="admin__control-text" id="layout_name" name="layout_name" value="<?php if(!empty($layout_name)) echo $layout_name; ?>">
                </div>
            </div>
        </div>
        
        <div id="show_error"></div>
    </fieldset>
</form>
