<?php
    $helper = \Magento\Framework\App\ObjectManager::getInstance()->get('Knowband\Mobileappbuilder\Helper\Data');
    $categories = $helper->getCategories();
    $products = $helper->getProductCollection();
?>
<form action="<?php echo $this->getUrl('*/*/saveAndSendPushNotification'); ?>" method="post" enctype="multipart/form-data" id="form_send_notification">
    <input type="hidden" id="form_key" name="form_key" value="<?php echo $this->getFormKey(); ?>" />
    <fieldset class="admin__fieldset"> 
       <div class="admin__field">
            <label class="admin__field-label" for="title">
                <span>
                    <span class="vss_required">*</span> <?php echo __("Title"); ?>
                </span>
            </label>
            <div class="admin__field-control">
                <div class="admin__control">
                    <input type="text" class="admin__control-text" id="title" name="notification[title]" value="">
                </div>
            </div>
        </div>
        <div class="admin__field">
            <label class="admin__field-label" for="message">
                <span>
                    <span class="vss_required">*</span> <?php echo __("Message"); ?>
                </span>
            </label>
            <div class="admin__field-control">
                <div class="admin__control">
                    <textarea class="admin__control-text" id="message" name="notification[message]"></textarea>
                </div>
            </div>
        </div>
        <div class="admin__field">
            <label class="admin__field-label" for="device_type">
                <span>
                    <span class="vss_required">*</span> <?php echo __("Select Brodcast Device Type"); ?>
                </span>
            </label>
            <div class="admin__field-control">
                <div class="admin__control">
                    <select name='notification[device_type]' id="device_type" class='admin__control-select'>
                        <option value='both' selected="selected" ><?php echo __("Both Android/iOS"); ?></option>
                        <option value='android' ><?php echo __("Android"); ?></option>
                        <option value='ios' ><?php echo __("iOS"); ?></option>
                    </select>
                </div>
            </div>
        </div>
        <div class="admin__field">
            <label class="admin__field-label" for="image_type">
                <span>
                    <span class="vss_required">*</span> <?php echo __("Select Image Type"); ?>
                </span>
            </label>
            <div class="admin__field-control">
                <div class="admin__control">
                    <select name='notification[image_type]' id="image_type" class='admin__control-select'>
                        <option value='0' selected="selected" ><?php echo __("Select an option"); ?></option>
                        <option value='url' ><?php echo __("URL"); ?></option>
                        <option value='image' ><?php echo __("Upload"); ?></option>
                    </select>
                </div>
            </div>
        </div>

        <div class="admin__field image_upload_sec" style="display: none;">
            <label class="admin__field-label" for="image_upload">
                <span><span class="vss_required">*</span>
                    <?php echo __("Upload Image")?></span>
            </label>
            <div class="admin__field-control">
                <div class="admin__actions-switch">
                    <div class="banner_block">
                        <img id="upload_image_preview" src="<?php echo $this->getViewFileUrl('Knowband_Mobileappbuilder::images/no_image.jpg'); ?>" style="margin: 0px 2px 3px 0px;width: 200px;height: 200px;border: 1px solid whitesmoke;" align="absmiddle">
                        <input id="remove-button" style="display: none;" class="action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" onclick="removeImage('image_upload_sec');" type="button" value="<?php echo __('Remove Image'); ?>">
                    </div>
                    <input onchange="readURL(this);" name="notification[image_upload]" id="image_upload" type="file" class="action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only banner-upload-btn" style="padding: 10px;background: whitesmoke;display: block;"/>
                    <input name="is_uploaded" id="is_uploaded" type="hidden" value="0"/>
                </div>
                <div class="vss_info">
                        <?php echo __("Only .png or .jpg file format accepted. File size should not be more than 2 MB.")?>
                    </div>
            </div>
        </div>

        <div class="admin__field image_url_sec" style="display: none;">
            <label class="admin__field-label" for="image_url">
                <span><span class="vss_required">*</span>
                    <?php echo __("Image Url")?></span>
            </label>
            <div class="admin__field-control">
                <div class="admin__actions-switch">
                    <div class="banner_block">
                        <img id="url_image_preview" src="<?php echo $this->getViewFileUrl('Knowband_Mobileappbuilder::images/no_image.jpg'); ?>" style="margin: 0px 2px 3px 0px;width: 200px;height: 200px;border: 1px solid whitesmoke;" align="absmiddle">
                        <input id="remove-button" style="display: none;" class="action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" onclick="removeImage('image_url_sec');" type="button" value="<?php echo __('Remove Image'); ?>">
                    </div>
                    <input name="notification[image_url]" id="image_url" placeholder="<?php echo __('Enter URL'); ?>" type="url" class="action-default scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only banner-upload-btn" style="padding: 10px;background: whitesmoke;display: block;"/>
                </div>
            </div>
        </div>

        <div class="admin__field">
            <label class="admin__field-label" for="redirect_activity">
                <span>
                    <span class="vss_required">*</span> <?php echo __("Select Redirect Activity"); ?>
                </span>
            </label>
            <div class="admin__field-control">
                <div class="admin__control">
                    <select name='notification[redirect_activity]' id="redirect_activity" class='admin__control-select'>
                        <option value='home' selected="selected" ><?php echo __("Home"); ?></option>
                        <option value='category' ><?php echo __("Category"); ?></option>
                        <option value='product' ><?php echo __("Product"); ?></option>
                    </select>
                </div>
            </div>
        </div>

        <div class="admin__field category_sec" style="display: none;">
            <label class="admin__field-label" for="category_id">
                <span>
                    <span class="vss_required">*</span> <?php echo __("Select Category"); ?>
                </span>
            </label>
            <div class="admin__field-control">
                <div class="admin__control">
                    <select name='notification[category_id]' id="category_id" class='admin__control-select'>
                        <?php foreach($categories as $cat_data) { ?>
                            <option value='<?php echo $cat_data['value']; ?>' ><?php echo $cat_data['label']; ?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>
        </div>

        <div class="admin__field product_sec" style="display: none;">
            <label class="admin__field-label" for="product_id">
                <span>
                    <span class="vss_required">*</span> <?php echo __("Select Product"); ?>
                </span>
            </label>
            <div class="admin__field-control">
                <div class="admin__control">
                    <select name='notification[product_id]' id="product_id" class='admin__control-select'>
                        <option value="0"><?php echo __('--Select Product--'); ?></option>
                        <?php
                            foreach ($products as $product) {
                                    $entity_id = $product->getId();
                                    $name = $product->getName(); ?>
                                    <option value="<?php echo $entity_id; ?>"><?php echo $name; ?></option>
                        <?php } ?>	
                    </select>
                    <input type="hidden" name="product_name" id="product_name"/>
                    <input type="hidden" name="category_name" id="category_name"/>
                </div>
            </div>
        </div>
        <div id="show_error"></div>
    </fieldset>
</form>
<script>
    function readURL(input) {
        require(['jquery'], function(jQuery){
            if (input.files && input.files[0]) {
              var reader = new FileReader();

              reader.onload = function(e) {
                jQuery('#new_noti_popup #upload_image_preview').attr('src', e.target.result);

                jQuery('#new_noti_popup #upload_image_preview').hide();
                jQuery('#new_noti_popup #upload_image_preview').fadeIn(650);
                jQuery('#new_noti_popup .image_upload_sec #remove-button').show();
                jQuery('#new_noti_popup #is_uploaded').val('1');
              }
              reader.readAsDataURL(input.files[0]);
            }
      });
    }
</script>