<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_Affiliate
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license     http://cedcommerce.com/license-agreement.txt
 */


/** @var \Ced\Affiliate\Block\Referral\Payout\Payout $block */
$earnedAmount=$block->pendingAmount();
$amount = $block->getAmount();
if(!$amount)
	$amount=1;

$gap=intval($earnedAmount/$amount);
for($i=1; $gap>=$i; $i++){
    $options[]=$amount*$i;
}

 ?>
 <div class="aff-title">
    <h2><? echo __('Payout Discount Coupon') ?></h2>
</div>
<div class="ced-discount-title-wrap">
    <div>
    <div class="panel-red">
        <div class="panel-heading" >
            <div class="info-heading" ><center><b><?php echo __('Your Current Balance: ')?> <?php echo $block->getFormattedPrice($earnedAmount) ?></b></center></div>
        </div>
    </div>
</div>
</div>
<div class="ced-discount-form-wrap">
<form action="<?php echo $this->getUrl('affiliate/payout/save') ?>" method="post" id="form-validate" class="form">
    <fieldset class="fieldset" data-hasrequired="* Required Fields">
        <legend class="legend"><span><?php echo __('Generate Discount Coupon')?></span></legend>
            <div class="ced-affiliate-coupon-wrap">
                <?php if(isset($options)): ?>
                    <div class="field firstname required">
                        <label for="discount_coupon" class="label"><?php echo __('Discount Coupon')?></label>
                        <div class="control">
                                <select name="discount_coupon" >
                                    <?php foreach ($options as $key => $value): ?>
                                        <option value="<?php echo $value ?>"><?php echo $block->getFormattedPrice($value) ?></option>
                                    <?php endforeach ?>
                                </select>
                        </div>
                    </div>
                    <div class="actions-toolbar">
                        <button name="submit" class="action primary" type="submit"><span><?php echo __('Submit')?></span></button>
                    </div>
                <?php else: ?>
                        <label><?php echo __('You did not reached the Payout Limit: ')?><?php echo $block->getFormattedPrice($amount) ?></label>
                <?php endif ?>
            </div>
    </fieldset>
</form>
</div>