<?php 
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_Affiliate
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license     http://cedcommerce.com/license-agreement.txt
 */
?>
<div class="aff-title">
        <h2><?php echo __('Transaction Summary') ?></h2>
</div>
<div class="affiliate-grid-wrapper">
<div class="block">
    <div class="block-title">
      <strong><?php echo __('Transaction List')?></strong>
    </div>
  </div>
	<?php
	echo $block->getGridHtml();
	?>
</div>