<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */
$_item = $block->getItem();
$_order = $block->getOrder();
//die(get_class($this));
?>
<div class="gstin-no">
</div>
<tr id="order-item-row-<?php /* @escapeNotVerified */ echo $_item->getId() ?>">
    <td class="col name" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
        <strong class="product name product-item-name"><?php echo $block->escapeHtml($_item->getName()) ?></strong>
 <?php if ($_options = $block->getItemOptions()): ?>
        <dl class="item-options">
        <?php foreach ($_options as $_option) : ?>
            <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
            <?php if (!$block->getPrintStatus()): ?>
                <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                <dd>
                    <?php if (isset($_formatedOptionValue['full_view'])): ?>
                        <?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?>
                    <?php else: ?>
                        <?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
                    <?php endif; ?>
                </dd>
            <?php else: ?>
                <dd>
                    <?php echo nl2br($block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value']))) ?>
                </dd>
            <?php endif; ?>
        <?php endforeach; ?>
        </dl>
        <?php endif; ?>
        <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addtInfoBlock) :?>
            <?php echo $addtInfoBlock->setItem($_item)->toHtml(); ?>
        <?php endif; ?>
        <?php echo $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="col sku" data-th="<?php echo $block->escapeHtml(__('SKU')); ?>"><?php 
    /* @escapeNotVerified */ 
    $i = 0;
    foreach (str_split($block->escapeHtml($block->getSku()), 10) as $_value) {
        if(!$i){
            echo $block->escapeHtml($_value);
        }else{

            echo '<br>'.$block->escapeHtml($_value);
        }
        $i++;
    }
    ?></td>
    
    
    <!-- Fetch Details Of GST -->
<?php 
    $gstRate = 'NULL';
    $igstRate = 'NULL';
    $gstAmt = 'NULL';
    $igstAmt = 'NUll';
    $amt = '';
	$gstHelper = $this->helper('Ced\CsGst\Helper\Data');
    $vendorId = $gstHelper->create('Ced\CsMarketplace\Model\Vproducts')->getVendorIdByProduct($_item->getProductId());
    if($vendorId){
    	$warehouse =  $gstHelper->getWarehouseForVendor($vendorId);
    }else{
    	$warehouse =  $gstHelper->getWarehouseForAdmin();
    }
    if(!$_order->getShippingAddress()){
    
    	$regionSelector = $_order->getBillingAddress();
    }else{
    	$regionSelector = $_order->getShippingAddress();
    }
    $regionId = $regionSelector->getRegionId();
    if ($regionId == $warehouse) { 
            $rate = $_item->getTaxPercent();
            $amt = $_item->getTaxAmount()/2;
            $gstAmt =$_item->getOrder()->formatPrice($amt);
            $gstRate = ($rate/2).'%';
       

?>
<!-- IGST -->
    <td>
        <?php echo 'N/A'; ?>
    </td>
<!-- CGST -->
    <td>
            <?php echo $gstAmt; ?>
            <div>
                <strong><?php echo __('Rate:'); ?></strong>
                <?php echo $gstRate; ?>
            </div>
        
    </td>
<!-- SGST -->
    <td>
            <?php echo $gstAmt; ?>
            <div>
                <strong><?php echo __('Rate:'); ?></strong>
                <?php echo $gstRate; ?>
            </div>
        
    </td>
<?php    }else{ 
    $igstAmt = $_item->getOrder()->formatPrice($_item->getTaxAmount());
    $igstRate = (int)$_item->getTaxPercent().'%';
?>
<!-- IGST -->
    <td>
        <?php echo $igstAmt; ?>
        <div>
            <strong><?php echo __('Rate:'); ?></strong>
            <?php echo $igstRate; ?>
        </div>
    </td>
<!-- CGST -->
    <td>
        <?php echo 'N/A'; ?>
    </td>
<!-- SGST -->
    <td>
        <?php echo 'N/A'; ?>
    </td>
<?php
        
    }
?>
    
    
    
    
    
    
    <td class="col price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
        <?php echo $block->getItemPriceHtml(); ?>
    </td>
    <td class="col qty" data-th="<?php echo $block->escapeHtml(__('Qty')); ?>">
        <ul class="items-qty">
        <?php if ($block->getItem()->getQtyOrdered() > 0): ?>
            <li class="item">
                <span class="title"><?php /* @escapeNotVerified */ echo __('Ordered'); ?></span>
                <span class="content"><?php /* @escapeNotVerified */ echo $block->getItem()->getQtyOrdered()*1 ?></span>
            </li>
        <?php endif; ?>
        <?php if ($block->getItem()->getQtyShipped() > 0): ?>
            <li class="item">
                <span class="title"><?php /* @escapeNotVerified */ echo __('Shipped'); ?></span>
                <span class="content"><?php /* @escapeNotVerified */ echo $block->getItem()->getQtyShipped()*1 ?></span>
            </li>
        <?php endif; ?>
        <?php if ($block->getItem()->getQtyCanceled() > 0): ?>
            <li class="item">
                <span class="title"><?php /* @escapeNotVerified */ echo __('Canceled'); ?></span>
                <span class="content"><?php /* @escapeNotVerified */ echo $block->getItem()->getQtyCanceled()*1 ?></span>
            </li>
        <?php endif; ?>
        <?php if ($block->getItem()->getQtyRefunded() > 0): ?>
            <li class="item">
                <span class="title"><?php /* @escapeNotVerified */ echo __('Refunded'); ?></span>
                <span class="content"><?php /* @escapeNotVerified */ echo $block->getItem()->getQtyRefunded()*1 ?></span>
            </li>
        <?php endif; ?>
        </ul>
    </td>
    <td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal')); ?>">
        <?php echo $block->getItemRowTotalHtml(); ?>
    </td>
</tr>
