<?php
/**
 * CedCommerce
*
* NOTICE OF LICENSE
*
* This source file is subject to the End User License Agreement (EULA)
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* https://cedcommerce.com/license-agreement.txt
*
* @category    Ced
* @package     Ced_ReferralSystem
* @author 		CedCommerce Core Team <connect@cedcommerce.com>
* @copyright   Copyright CedCommerce (https://cedcommerce.com/)
* @license      https://cedcommerce.com/license-agreement.txt
*/
$coupons = $block->getCollection();
//$priceHelper = $block->helper('\Magento\Framework\Pricing\Helper\Data');
$view_model = $block->getViewModel();
?>

<div class="col-md-12" style="padding-top:15px">
    <div class="table-wrapper-1">
        <legend class="legend"><span><?= /* @noEscape */ __('Your Discount Coupons'); ?></span></legend>
        <?php if(isset($coupons) && $coupons->count()>0): ?>
             <div class="table_responsive">
                <div class="table_responsive_inner">
                    <table class="data-table">
                        <thead>
                            <tr>
                                <th><?= /* @noEscape */ __('Coupon Code');?></th>
                                <th><?= /* @noEscape */ __('Amount');?></th>
                                <th><?= /* @noEscape */ __('Created At');?></th>
                                <th><?= /* @noEscape */ __('Valid Till');?></th>
                                <th><?= /* @noEscape */ __('Status');?></th>
                                <th class="content-right"><?= /* @noEscape */ __('Purchase Required');?></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $i=1; ?>
                            <?php foreach($coupons as $value): ?>
                                <?php $coupon_used = $block->getDiscountCouponStatus($value["coupon_code"]);
                                    if($coupon_used == 2){
                                        $status = 'Unused';
                                    }else{
                                        $status = 'Used';
                                    }
                                ?>
                                    <tr>
                                        <td><?= /* @noEscape */ $value["coupon_code"] ?></td>
                                        <td><?= /* @noEscape */ $view_model->CurrencyFormatter($value["amount"]); ?></td>
                                        <td><?= /* @noEscape */ $block->getViewModel()->getDateTime($value["created_at"]); ?></td>
                                        <td><?= /* @noEscape */ $block->getViewModel()->getDateTime($value["expiration_date"]); ?></td>
                                        <td><?= /* @noEscape */ $status ?></td>
                                        <td class="content-right"><?= /* @noEscape */ $view_model->CurrencyFormatter($value["cart_amount"]); ?></td>
                                   </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
            <?php if ($block->getPagerHtml()): ?>
                <div class="toolbar toolbar-list"><?= /* @noEscape */ $block->getPagerHtml(); ?></div>
            <?php endif; ?>
        <?php else: ?>
            <div class="col-md-12">
                <label><?= /* @noEscape */ __('No discount coupons are currently available!'); ?></label>
            </div>
        <?php endif; ?>
    </div>
</div>
