<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_item = $block->getItem() ?>
<?php $_order = $block->getItem()->getOrder(); ?>
<tr>
    <td class="item-info<?php if ($block->getItemOptions()): ?> has-extra<?php endif; ?>">
        <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
       
        <p class="sku"><?= /* @escapeNotVerified */  __('SKU'); ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
        <?php if ($block->getItemOptions()): ?>
            <dl>
                <?php foreach ($block->getItemOptions() as $option): ?>
                    <dt><strong><em><?= /* @escapeNotVerified */  $option['label'] ?></em></strong></dt>
                    <dd>
                        <?= /* @escapeNotVerified */  nl2br($option['value']) ?>
                    </dd>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?= $addInfoBlock->setItem($_item->getOrderItem())->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <!-- Fetch Details Of GST -->
<?php 
    $gstRate = 'NULL';
    $igstRate = 'NULL';
    $gstAmt = 'NULL';
    $igstAmt = 'NUll';
    $amt = '';
	$gstHelper = $this->helper('Ced\CsGst\Helper\Data');
    $vendorId = $gstHelper->create('Ced\CsMarketplace\Model\Vproducts')->getVendorIdByProduct($_item->getProductId());
    if($vendorId){
    	$warehouse =  $gstHelper->getWarehouseForVendor($vendorId);
    }else{
    	$warehouse =  $gstHelper->getWarehouseForAdmin();
    }
    if(!$_order->getShippingAddress()){
    
    	$regionSelector = $_order->getBillingAddress();
    }else{
    	$regionSelector = $_order->getShippingAddress();
    }
    $regionId = $regionSelector->getRegionId();
    if ($regionId == $warehouse) {
            $rate = $_item->getTaxPercent();
            $amt = $_item->getTaxAmount()/2;
            $gstAmt =$_order->formatPrice($amt);
            $gstRate = ($rate/2).'%';
?>
<!-- IGST -->
    <td>
        <?php echo 'N/A'; ?>
    </td>
<!-- CGST -->
    <td>
            <?php echo $gstAmt; ?>
            <div>
            <strong><?php echo __('Rate:'); ?></strong>
            <?php echo $gstRate; ?>
        </div>
            
        
    </td>
<!-- SGST -->
    <td>
            <?php echo $gstAmt; ?>
          <div>
            <strong><?php echo __('Rate:'); ?></strong>
            <?php echo $gstRate; ?>
        </div>
           
        
    </td>
<?php    }else{
    $igstAmt = $_order->formatPrice($_item->getTaxAmount());
    $igstRate = (int)$_item->getTaxPercent().'%';
?>
<!-- IGST -->
    <td>
        <?php echo $igstAmt; ?>
        <div>
            <strong><?php echo __('Rate:'); ?></strong>
            <?php echo $igstRate; ?>
        </div>
       
    </td>
<!-- CGST -->
    <td>
        <?php echo 'N/A'; ?>
    </td>
<!-- SGST -->
    <td>
        <?php echo 'N/A'; ?>
    </td>
<?php
        
    }
?>
    <td class="item-qty"><?= /* @escapeNotVerified */  $_item->getQty() * 1 ?></td>
    <td class="item-price">
        <?= /* @escapeNotVerified */  $block->getItemPrice($_item); ?>
    </td>  
</tr>
