<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_Affiliate
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license     http://cedcommerce.com/license-agreement.txt
 */

$referred_list = $this->getCollection();

if(isset($referred_list) && $referred_list->count()>0){?>
<div style="overflow-x:auto;">
		<table class="data-table" id="my-orders-table">
			<thead>
				<tr>
					<th><?php echo __('Description');?></th>
					<th><?php echo __('Amount');?></th>
					<th><?php echo __('Transaction Type');?></th>
					<th><?php echo __('Date');?></th>
					
				</tr>
			</thead>
			<tbody>
		<?php
		foreach($referred_list as $value){ ?>
				<tr>
						<td><?php echo $value["description"]  ?></td>
						<td><?php echo $block->getFormattedPrice($value["earned_amount"]) ?></td>
						<td><?php if($value["transaction_type"]==1){
							echo "CREDIT";
							}else{
								echo "DEBIT";
								} ?></td>
						<td><?php echo $value["creation_date"] ?></td>
			   </tr>
		<?php }?>

			</tbody>
		</table>
</div>
<?php if ($block->getPagerHtml()): ?>
<div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
<?php endif; ?>
<?php }else{?>
<h3><?php echo __('You had not referred any friends.')?></h3>
<?php }?>


<style>
table thead{
	background-color: #006BB4;
}
table tr th{
	font-weight: bold;
	color:white;
}
table tr td{
	width:12%;

}
</style>