<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsPromotions
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */

// @codingStandardsIgnoreFile

?>
<style>
    .admin__field-label{
        color: #000 !important;
    }
</style>
<?php $_element = $block->getElement() ?>
<div class="rule-tree">
    <fieldset id="<?php echo $_element->getHtmlId() ?>" <?php /* @escapeNotVerified */ echo $_element->serialize(['class']) ?> class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo $_element->getLegend() ?></span></legend>
        <br>
        <?php if ($_element->getComment()): ?>
            <div class="messages">
                <div class="message message-notice"><?php echo $block->escapeHtml($_element->getComment()) ?></div>
            </div>
        <?php endif; ?>
        <div class="rule-tree-wrapper">
            <?php echo $_element->getChildrenHtml() ?>
        </div>
    </fieldset>
</div>
<script>
    require([
        "Ced_CsPromotions/js/rules",
        "prototype"
    ], function(VarienRulesForm){

        window.<?php echo $_element->getHtmlId() ?> = new VarienRulesForm('<?php echo $_element->getHtmlId() ?>', '<?php /* @escapeNotVerified */ echo $block->getNewChildUrl() ?>');
        <?php if ($_element->getReadonly()): ?>
        <?php echo $_element->getHtmlId() ?>.setReadonly(true);
        <?php endif; ?>

    });
</script>
