<?php 
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_Affiliate
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license     http://cedcommerce.com/license-agreement.txt
 */
?>
<style>
.signup:hover {
    background-color:#f2703e;
    color:white;
}
</style>

			<!--<div class="col-button">-->
			<div class="name affilatehead"><p style="font-size:30px;">Affiliate</p></div>
			
			<hr style="width:100%;">
			<div class="button aff" style="padding:2rem 0 rem;">
			    <div class="info"><p style="float:left;"><b>Be part of our program to spread the word of goodness and get rewarded.</b></p>
			    <button
			        onclick="location.href='<?php echo $this->getUrl('affiliate/account/login')?>'"
			        <div class="signup affiliate" style="float:right;">
			            <span><?php echo __('Login/Signup')?></span></div>
			        
			    </button>
			   
			    <div class="banner signin">
			        <img src="<?php echo $block->getViewFileUrl('Ced_Affiliate/images/affiliate.png');?>" alt="Affiliate_banner"/>
			    </div>
			    <div class="discription underbanner" style="margin-top:20px;">
			        <p>Anyone with a good network can register to become part of our affiliate program. Our affiliate program rewards affiliates with attractive commissions. Affiliates can reach out their network through social media using a unique link or unique coupon codes. Affiliates can monitor and track their transactions through affiliate panel. Be part of our program to spread the word of goodness and get rewarded.</p><br>
			        <p><b>For more details Click <a href="https://homedirect.in/hdaffiliate">Here</a>&nbsp;&nbsp;&nbsp;<a href="https://homedirect.in/index.php/default/affiliate/account/create/">Sign Up</a></b></p>
			    </div>
			    
			</div>
			
	


