<!-- /**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_Inventory
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */-->
<!--@subject MY EMAIL SUBJECT HERE @-->
{{template config_path="design/email/header_template"}}
<table><tr class="email-intro"><td>
            <p class="greeting">{{trans "%myname," customer_name=$data.myname}}</p>
            <p class="greeting">{{trans "%myemail," customer_email=$data.myemail}}</p>
        </td></tr></table>
{{template config_path="design/email/footer_template"}}